version: "3.9"

volumes:
  uitslagen-db:
  uitslagen-exports:

services:
  uitslagen-server:
    image: docker.nilsb.nl/uitslagen-atletiek.nl:latest
    container_name: Uitslagen-Server
    restart: always
    ports:
      - '5000:5000'
    expose:
      - '5000'
    volumes:
      - uitslagen-db:/home/uitslagen/database
      - uitslagen-exports:/home/uitslagen/app/static/export