version: "3.9"

services:
  uitslagen-server:
    image: nilsbebelaar/uitslagen-atletiek.nl:latest
    container_name: Uitslagen Server
    restart: always
    ports:
      - '5000:5000'
    expose:
      - '5000'
    environment:
      - FLASK_DEBUG=False
      - FLASK_TESTING=False
