name: Build and push Docker images

on:
  push:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
     - 
      name: Checkout repository
      uses: actions/checkout@v4
     - 
      name: Set environment variables
      run: |
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
     -
      name: Connect to Tailnet
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:github-actions
     -
      name: Configure Docker to allow insecure registry
      run: |
        echo '{ "insecure-registries": ["atlas:5555"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        # Verify the configuration (optional)
        sudo cat /etc/docker/daemon.json
        docker info | grep "Insecure Registries"
     -
      name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: atlas:5555
        username: ${{ secrets.DOCKER_LOGIN_NAME }}
        password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
     - 
      name: Build and Push
      uses: docker/build-push-action@v6.9.0
      with:
        file: Dockerfile
        tags: |
          atlas:5555/uitslagen-atletiek.nl:latest
        push: true
